const C=window.APP_CONFIG||{}, sb=(window.supabase&&C.SUPABASE_URL)?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
let assets=[],role='viewer',user=null,page=1; const PAGE=50;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const areas=['RDS A','RDS B','HMP A','HMP B','PACKING A','PACKING B','PELLETIZING','SILO','ENGINEERING','OFFICE','OPERATIONAL','WAREHOUSE','UTILITY','LABORATORY','SECURITY','MESS','WWTP','GOH','GAD','AREA BELUM DITENTUKAN'];
const markerPos={'RDS A':[55,59],'RDS B':[68,59],'HMP A':[43,66],'HMP B':[56,69],'PACKING A':[35,75],'PACKING B':[51,78],SILO:[58,61],ENGINEERING:[25,53],OFFICE:[18,45],OPERATIONAL:[28,34],WAREHOUSE:[64,37],UTILITY:[77,71],LABORATORY:[20,83],SECURITY:[13,57],WWTP:[73,88]};
function classify(fun='',plant='',tag=''){const s=`${plant} ${fun} ${tag}`.toUpperCase(),rules=[['RDS A',/RDY01|RDS\s*A\b|RDSA/],['RDS B',/RDY02|RDS\s*B\b|RDSB/],['HMP A',/HML01|HMP\s*A\b|HMPA/],['HMP B',/HML02|HMP\s*B\b|HMPB/],['PACKING A',/PCK01|PACK(?:ING)?\s*A\b/],['PACKING B',/PCK02|PACK(?:ING)?\s*B\b/],['ENGINEERING',/ENG01|ENGINEER|WORKSHOP/],['OFFICE',/OFFICE|ADMIN/],['OPERATIONAL',/OPERATIONAL|OPERASIONAL/],['WAREHOUSE',/WAREHOUSE|GUDANG|\bWH\b/],['UTILITY',/UTILITY|\bUTY\b|GEN01/],['LABORATORY',/LABORATORY|\bLAB\b/],['SECURITY',/SECURITY|SATPAM/],['MESS',/\bMESS\b/],['WWTP',/WWTP|WASTE/],['PELLETIZING',/PELLET/],['SILO',/SILO/],['GOH',/\bGOH\b/],['GAD',/\bGAD\b/]];return (rules.find(x=>x[1].test(s))||[])[0]||plant.toUpperCase()||'AREA BELUM DITENTUKAN'}
function stableId(a){const s=[a.category,a.functional_location,a.equipment_no,a.tagname].join('|').toUpperCase();let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return 'a'+(h>>>0).toString(16)+btoa(unescape(encodeURIComponent(s))).replace(/\W/g,'').slice(0,11)}
async function init(){assets=await fetch('assets/assets.json').then(r=>r.json());if(sb){const {data:{session}}=await sb.auth.getSession();if(session)await applyUser(session.user);const online=[];let from=0,loadError=null;while(true){const {data,error}=await sb.from('assets').select('*').range(from,from+999);if(error){loadError=error;break}if(!data?.length)break;online.push(...data);if(data.length<1000)break;from+=1000}if(!loadError&&online.length)assets=online;sb.auth.onAuthStateChange(async(_,s)=>{if(s)await applyUser(s.user);else applyViewer()})}fillFilters();renderAll();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));['search','areaFilter','categoryFilter','statusFilter'].forEach(id=>$(id).oninput=()=>{page=1;renderTable()});$('mapArea').onchange=()=>openArea($('mapArea').value);$('globalSearch').oninput=e=>$('search').value=e.target.value;$('loginBtn').onclick=()=>$('loginModal').classList.remove('hidden');$('logoutBtn').onclick=()=>sb?.auth.signOut();$('loginForm').onsubmit=login;$('editForm').onsubmit=saveAsset}
async function applyUser(u){user=u;role=u.email?.toLowerCase()===C.ADMIN_EMAIL.toLowerCase()?'administrator':'technician';if(sb&&role!=='administrator'){const {data}=await sb.from('profiles').select('role').eq('id',u.id).maybeSingle();role=data?.role||'technician'}updateAccess()}
function applyViewer(){user=null;role='viewer';updateAccess();showView('dashboard')}
function updateAccess(){$('roleBadge').textContent=role.toUpperCase();$('loginBtn').classList.toggle('hidden',!!user);$('logoutBtn').classList.toggle('hidden',!user);$('addBtn').classList.toggle('hidden',role!=='administrator');$('manageBtn').classList.toggle('hidden',role!=='administrator');renderTable()}
async function login(e){e.preventDefault();$('loginError').textContent='';if(!sb)return $('loginError').textContent='Supabase belum tersedia.';const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('loginError').textContent=error.message;else closeModal('loginModal')}
function closeModal(id){$(id).classList.add('hidden')}
function showView(id){if(id==='manage'&&role!=='administrator')return;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));if(id==='assets')renderTable();scrollTo(0,0)}
function counts(){return assets.reduce((o,a)=>(o[a.area_group]=(o[a.area_group]||0)+1,o),{})}
function fillFilters(){const unique=k=>[...new Set(assets.map(a=>a[k]).filter(Boolean))].sort();$('areaFilter').innerHTML='<option value="">Semua Area</option>'+unique('area_group').map(x=>`<option>${esc(x)}</option>`).join('');$('categoryFilter').innerHTML='<option value="">Semua Category</option>'+unique('category').map(x=>`<option>${esc(x)}</option>`).join('');$('mapArea').innerHTML='<option value="">Pilih area...</option>'+unique('area_group').map(x=>`<option>${esc(x)}</option>`).join('');$('fArea').innerHTML=[...new Set([...areas,...unique('area_group')])].sort().map(x=>`<option>${esc(x)}</option>`).join('')}
function renderAll(){const n=counts(),cats=new Set(assets.map(a=>a.category)).size,active=assets.filter(a=>a.status==='Active').length,unknown=assets.filter(a=>a.area_group==='AREA BELUM DITENTUKAN').length;$('kpis').innerHTML=[['Total Aset',assets.length],['Kategori',cats],['Aset Aktif',active],['Perlu Mapping',unknown]].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1].toLocaleString('id-ID')}</b></div>`).join('');const sorted=Object.entries(n).sort((a,b)=>b[1]-a[1]),max=sorted[0]?.[1]||1;$('areaChart').innerHTML=sorted.map(([k,v])=>`<div class="bar-row" onclick="openArea('${esc(k)}')"><div class="bar-label"><span>${esc(k)}</span><b>${v}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('');$('markers').innerHTML=sorted.filter(([k])=>markerPos[k]).map(([k,v])=>`<button class="marker" style="left:${markerPos[k][0]}%;top:${markerPos[k][1]}%" onclick="openArea('${k}')">${esc(k)} · ${v}</button>`).join('');$('recent').innerHTML='<div class="mini-list">'+assets.slice(-8).reverse().map(a=>`<div class="mini"><b>${esc(a.tagname||'-')}</b><span>${esc(a.functional_location||'-')}</span><span>${esc(a.area_group)}</span></div>`).join('')+'</div>';renderTable()}
function filtered(){const q=$('search').value.toLowerCase(),ar=$('areaFilter').value,ca=$('categoryFilter').value,st=$('statusFilter').value;return assets.filter(a=>(!q||Object.values(a).some(v=>String(v).toLowerCase().includes(q)))&&(!ar||a.area_group===ar)&&(!ca||a.category===ca)&&(!st||a.status===st))}
function renderTable(){if(!$('assetRows'))return;const list=filtered(),pages=Math.max(1,Math.ceil(list.length/PAGE));page=Math.min(page,pages);$('assetCount').textContent=`${list.length.toLocaleString('id-ID')} aset ditemukan`;const slice=list.slice((page-1)*PAGE,page*PAGE);$('assetRows').innerHTML=slice.map(a=>`<tr><td>${esc(a.category)}</td><td><b>${esc(a.tagname||'-')}</b></td><td class="wrap">${esc(a.functional_location||'-')}</td><td>${esc(a.equipment_no||'-')}</td><td>${esc(a.plant_area||'-')}</td><td>${esc(a.area_group)}</td><td><span class="status">${esc(a.status||'Active')}</span></td><td>${role==='viewer'?'<button onclick="viewAsset(\''+a.id+'\')">Detail</button>':'<button onclick="openEditor(\''+a.id+'\')">Edit</button>'}${role==='administrator'?` <button class="danger" onclick="deleteAsset('${a.id}')">Hapus</button>`:''}</td></tr>`).join('');$('pager').innerHTML=`<button ${page<=1?'disabled':''} onclick="page--;renderTable()">‹</button><span>${page} / ${pages}</span><button ${page>=pages?'disabled':''} onclick="page++;renderTable()">›</button>`}
function openArea(a){if(!a)return;$('areaFilter').value=a;$('search').value='';page=1;showView('assets')}
function viewAsset(id){openEditor(id,true)}
function openEditor(id,readonly=false){$('editForm').querySelectorAll('input,select,textarea').forEach(x=>x.disabled=false);const a=assets.find(x=>x.id===id)||{};$('editTitle').textContent=readonly?'Detail Aset':(id?'Edit Aset':'Tambah Aset');$('assetId').value=a.id||'';$('fCategory').value=a.category||'';$('fTagname').value=a.tagname||'';$('fFunloc').value=a.functional_location||'';$('fEquipment').value=a.equipment_no||'';$('fPlant').value=a.plant_area||'';$('fArea').value=a.area_group||'AREA BELUM DITENTUKAN';$('fBrand').value=a.brand||'';$('fModel').value=a.model||'';$('fStatus').value=a.status||'Active';$('fCondition').value=a.condition||'Unknown';$('fPhoto').value=a.photo_url||'';$('fRemark').value=a.remark||'';const restricted=role==='technician';['fCategory','fTagname','fFunloc','fEquipment','fPlant','fArea','fBrand','fModel'].forEach(x=>$(x).disabled=readonly||restricted);$('editForm').querySelector('button[type=submit]').classList.toggle('hidden',readonly);$('editForm').querySelectorAll('input,select,textarea').forEach(x=>{if(readonly)x.disabled=true});$('editModal').classList.remove('hidden')}
async function saveAsset(e){e.preventDefault();const old=assets.find(x=>x.id===$('assetId').value),a={...(old||{}),category:$('fCategory').value.trim(),tagname:$('fTagname').value.trim(),functional_location:$('fFunloc').value.trim(),equipment_no:$('fEquipment').value.trim(),plant_area:$('fPlant').value.trim(),area_group:$('fArea').value,brand:$('fBrand').value.trim(),model:$('fModel').value.trim(),status:$('fStatus').value,condition:$('fCondition').value,photo_url:$('fPhoto').value.trim(),remark:$('fRemark').value.trim(),updated_at:new Date().toISOString()};a.id=old?.id||stableId(a);$('saveError').textContent='';if(sb){const {error}=await sb.from('assets').upsert(a);if(error)return $('saveError').textContent=error.message}const i=assets.findIndex(x=>x.id===a.id);i<0?assets.push(a):assets[i]=a;closeModal('editModal');fillFilters();renderAll()}
async function deleteAsset(id){if(role!=='administrator'||!confirm('Hapus aset ini?'))return;if(sb){const {error}=await sb.from('assets').delete().eq('id',id);if(error)return alert(error.message)}assets=assets.filter(a=>a.id!==id);renderAll()}
function exportCSV(){const cols=['category','tagname','functional_location','equipment_no','object_type','plant_area','area_group','brand','model','condition','status','remark','photo_url'],q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv='\ufeff'+[cols,...filtered().map(a=>cols.map(k=>a[k]))].map(r=>r.map(q).join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='PIM-Asset-Register.csv';a.click();URL.revokeObjectURL(u)}
async function importExcel(){if(role!=='administrator')return;const f=$('excelFile').files[0];if(!f)return $('importStatus').textContent='Pilih file Excel terlebih dahulu.';$('importStatus').textContent='Membaca dan menyinkronkan...';try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),incoming=[];for(const name of wb.SheetNames){if(['SUMMARY','Equipments SAP','CC'].includes(name))continue;const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''}),hi=rows.findIndex(r=>r.some(v=>String(v).trim().toLowerCase()==='tagname'));if(hi<0)continue;const hs=rows[hi].map(v=>String(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()),idx=(...ks)=>{for(const k of ks){const i=hs.findIndex(h=>h.includes(k));if(i>=0)return i}return-1},ix={tag:idx('tagname'),fun:idx('function location','functional location'),eq:idx('equipment no'),obj:idx('object type'),plant:idx('plant area','plant location'),brand:idx('brand'),model:idx('model'),remark:idx('remark')};for(const r of rows.slice(hi+1)){const g=k=>ix[k]>=0?String(r[ix[k]]??'').trim():'';if(!g('tag')&&!g('fun')&&!g('eq'))continue;const a={category:name,tagname:g('tag'),functional_location:g('fun'),equipment_no:g('eq'),object_type:g('obj'),plant_area:g('plant'),area_group:classify(g('fun'),g('plant'),g('tag')),brand:g('brand'),model:g('model'),remark:g('remark'),status:'Active',condition:'Unknown',photo_url:'',updated_at:new Date().toISOString()};a.id=stableId(a);const old=assets.find(x=>x.id===a.id);incoming.push({...a,condition:old?.condition||a.condition,photo_url:old?.photo_url||'',status:old?.status||a.status,remark:a.remark||old?.remark||''})}}if(sb){for(let i=0;i<incoming.length;i+=500){const {error}=await sb.from('assets').upsert(incoming.slice(i,i+500));if(error)throw error}}const m=new Map(assets.map(a=>[a.id,a]));incoming.forEach(a=>m.set(a.id,a));assets=[...m.values()];fillFilters();renderAll();$('importStatus').textContent=`Selesai: ${incoming.length} baris diproses. Data dokumentasi lama tetap dipertahankan.`}catch(e){$('importStatus').textContent='Gagal: '+e.message}}
init().catch(e=>{console.error(e);alert('Aplikasi gagal dimuat: '+e.message)});
